[options]
# target multipart form /api/send
request =
--batch
--level=5
--risk=3
--dbs
--threads=4
--timeout=20
--retries=2
--ua=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
--technique=BEUSTQ
--tamper=space2comment
