#!/bin/bash
echo "=== CP env: scanner flags only (no secrets) ==="
docker exec scanner-cp printenv | grep -E '^(SCANNER_ENGINE_MAX_TURNS|SCANNER_ENGINE_MAX_WAVES|SCANNER_LEDGER_ATTEMPT_CAP|SCANNER_LEDGER_LEASE_S|SCANNER_ENGINE_WORKER_WALL_S|SCANNER_ENGINE_BATCH_DISPATCH|SCANNER_ENGINE_POOL_HARD_CAP|SCANNER_ENGINE_FANOUT|SCANNER_ENGINE_STUCK_WINDOW_S|SCANNER_ENGINE_SEAT_MODELS|SCANNER_ENGINE_BOSS|SCANNER_ORACLE_FIRST|SCANNER_EVIDENCE_GATE|SCANNER_LEDGER_MACHINE_CLOSE|SCANNER_LEDGER_SKILL_GATE|SCANNER_AUTH_ORACLES_ENABLED|SCANNER_GRAPHQL_AUTHZ_ENABLED|SCANNER_CHANNEL_ORACLES_ENABLED|SCANNER_AI_REDTEAM_FLOOR|SCANNER_EXECUTED_CHAIN_FINDINGS|SCANNER_ENGINE_ESCALATE|SCANNER_ENGINE_RECON_EXPANSION_ROUNDS|SCANNER_ENGINE_EXPANSION_BUDGET|SCANNER_TIME_CAP_S|SCANNER_ENGINE_LIVE_CONVERGENCE|SCANNER_ENGINE_SYNC_INTERVAL_S|SCANNER_ENGINE_RESUME|SCANNER_FLOOR_BUDGET_S|SCANNER_LEDGER_STOP_ON_PROBE|SCANNER_FINALIZE_RETIRE_UNREACHED|SCANNER_SSRF_CLOUD_EXFIL|SCANNER_DEFERRED_CONFIRMATION)='
echo "=== runtime_settings table (safe redaction) ==="
docker exec -i scanner-postgres psql -U scanner -d scanner -P pager=off <<'SQL'
SELECT key::text, CASE WHEN key::text ~* '(key|token|secret|password)' THEN 'REDACTED' ELSE value::text END AS value
FROM public.runtime_settings ORDER BY key::text;
SQL
echo "=== running scan: governor decisions + phases + method_switch count ==="
docker logs scanner-cp --since 12h 2>&1 | grep -Ei "governor|phase_started|finalize|salvag" | tail -n 15
