set -u
q() { docker exec scanner-postgres psql -U scanner -d scanner -X -A -F' | ' -t -c "$1" 2>&1; }
echo "=== N1 worker_runs aggregate ==="
q "select count(*) n, count(distinct scan_id) scans, count(distinct worker_id) workers, sum(case when status='error' then 1 else 0 end) err, sum(case when status='running' then 1 else 0 end) run, sum(coalesce(findings_count,0)) fnd, sum(coalesce(resolved_count,0)) res from tenant_xbow.worker_runs;"
echo "=== N2 worker_runs status census ==="
q "select coalesce(status,'<NULL>'), count(*) from tenant_xbow.worker_runs group by 1 order by 2 desc;"
echo "=== N3 tool_invocations aggregate ==="
q "select count(*), count(distinct scan_id), count(distinct agent_id), count(distinct tool_name) from tenant_xbow.tool_invocations;"
echo "=== N4 tool_invocations top tools ==="
q "select tool_name, count(*) from tenant_xbow.tool_invocations group by 1 order by 2 desc limit 20;"
echo "=== N5 tool_invocations status/exit ==="
q "select coalesce(status,'<NULL>'), count(*), sum(case when exit_code is null then 1 else 0 end) from tenant_xbow.tool_invocations group by 1 order by 2 desc;"
echo "=== N6 agent_messages turns per worker (top) ==="
q "select left(scan_id::text,8), agent_id, count(*) msgs, max(turn_index) maxturn, sum(coalesce(tokens_in,0)) tin, sum(coalesce(tokens_out,0)) tout, round(sum(coalesce(cost_usd,0))::numeric,4) cost from tenant_xbow.agent_messages group by 1,2 order by 3 desc limit 25;"
echo "=== N7 model census in agent_messages ==="
q "select coalesce(model,'<NULL>'), count(*) from tenant_xbow.agent_messages group by 1 order by 2 desc;"
echo "=== N8 RATIOS ==="
q "select 'messages_total', count(*)::text from tenant_xbow.agent_messages union all select 'worker_runs_total', count(*)::text from tenant_xbow.worker_runs union all select 'tool_invocations_total', count(*)::text from tenant_xbow.tool_invocations union all select 'findings_total', count(*)::text from tenant_xbow.findings union all select 'ledger_cells', count(*)::text from tenant_xbow.ledger_cell union all select 'evidence', count(*)::text from tenant_xbow.evidence_object;"
echo "=== N9 coverage_ledger / scan_events volume ==="
q "select 'coverage_ledger', count(*)::text from tenant_xbow.coverage_ledger union all select 'scan_events', count(*)::text from tenant_xbow.scan_events union all select 'inventory_element', count(*)::text from tenant_xbow.inventory_element union all select 'chain_node', count(*)::text from tenant_xbow.chain_node union all select 'checkpoints', count(*)::text from tenant_xbow.checkpoints;"